name: Mon SUPER workFLOW #Nom du workflow (affiche dans la console)
on: [push] # Evenement a partir duquel le WF est lancé
jobs: #Les regroupement d'étapes a appliquer lors du WF
  say-hello: #Le nom du job
    runs-on: ubuntu-latest #L'environnement sur lequel lancer le WF
    steps: #Listes des étapes du job
      - run: echo "Hello, World!" #1 étape du job
  hello-world: 
    runs-on: ubuntu-latest 
    steps:  
      - run: echo "hiii"
  build: 
    runs-on: ubuntu-latest
    steps:
    #{organisaitons}/{repertoire}@{version}
    - uses: actions/checkout@v4.2.2
    - run: ls
    - run: echo "Ce workflow a été trigger sur un événement de type ${{ github.event_name }}"
    - run: echo "L'utilisateur qui a déclanché l'action est ${{ github.actor }}"
    - run: echo "L'SHA du commit déclancheur est ${{ github.sha }}"
    - run: echo " Le nom de ce workflow est ${{ github.workflow }}"
    - run: echo " L'architecture CPU de ce runner est ${{ runner.arch }} "
    - run: echo "Le répertoire personnel de ce runner est ${{ env.HOME }}" 
    
